$ANSIBLE_VAULT;1.1;AES256
37353265393465326436666365373963336164366431336265386137323132303436356539396334
3734393463353133376330643165353734636231356237630a636430303066376265323230663832
32626236643332306466376164303131633365326531386537646234383466656465323835393964
3931323139666233310a386564316436356466343765666239336136656233316363613138393462
63623630313332656634373631343032643962613539646432626130353937626335303339613632
34346164363636386462323939376363656535613164623933356366373163353165383463396431
65363863303133643863616131383836383233326362356130393233353163353336363461396633
37643436363832386133386433643733643863323862346632396633383666363135356130626439
38616662376137353932313566633137303966666234393263303737623535386433623434626561
61656566383963393065346139646433346264373633376630353739373731346137366266313530
39656238373761623236303339333964646163373138393430316638323365333332343164346266
61353365646662376564333363613038323961316364646339623038373333373338313962396439
36376536316432616532626363616463323331366632356437356466323937343166353865353866
33356132666236633636366466373337326238396238323761306537613638643933353065383334
32343332356432363236326236613535663063663935643565353666613765616161643531373031
38396531323561333865316533616235643937636538356536626564643735663939383561316165
64353737386638346435323866373635633764383761363739323432376564626565353536663938
35393139333562383964363037343130313233626237333165373666343635656466663062613361
64383864363964333261666263643834633165613335613431383862666366313164663530646232
36363235353164363664656162323966666132316639316338616262353463303933333838333135
37613339656561303263363835623431616562306535316334663632653161656264393864646664
36663332323334393838666635323233613265653031353766663765626165336566633733353637
66373432346432333334386135663036333762353363353032346331313566383333316137653063
62613932336135363437336637333939623932333431303138616232386137653235653637343566
65393831306637393238376536303231353861303862623335303638356232633163303436646137
35626336313534653234633635353762666531363163666435646265623164366561636338346536
30356133336163633433393839326231383331636637353936346331386432306538346162303864
61646430313433306239636139663836616464656639363966333636343862613539343465313564
30626565366631373835626461346561326135653736626137326163383138383962633831396464
37353931376135376532316538376264656365353932613738633063626439353034636331313566
39626135333061356365306432303631616366343963633034653563303039373664653636633763
33336634323162303639623537653865636336393137373563646361343532343439323339616538
32353138303636316539313131383339306538663132303961656233656331643738353566353738
62303661363037393330326564323536383632363839663164363466613435386432333061393836
65633364353864393462623330306336623961383734353565646234636339363665333438346531
36383736646464383931313163653032663038393032656366353133623831313063303665666535
61363861366339336439666139313439306462363833333537636166323535316162343964666136
36326238626563346431313836633139656662316134303035303639353835656565386136356161
373365646235306163656430353566343335
