ansible_user: slava
ansible_ssh_private_key_file: /home/slava/.ssh/operator_key
ansible_ssh_common_args: "-o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no"
ansible_become: true
ansible_become_method: sudo
