$ANSIBLE_VAULT;1.1;AES256
62363431643461623139316166386131366638613131306630306638343035373436643965613131
6339623331646637613262623834376161333934333361310a646530656464356332336235313437
65633864663232386663653532623534646165366432643230353530306134393432333362613231
3238373033353962360a373934653036333731376664653131353161313932346565346161633330
34356562633066333531653130323938316564336436613536373165326233306337386336353434
31336161336336346164373136363965353261616433626236356266376264306337396366306163
66373734633636336334363135363033383237333164663330313561353137633434323333653335
62663566313565663963336334313437323362326263316135646364653536613137306131353432
66366261373062656635323732343131643063373134303762653335356135303265
